/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Ex3IndexRouteImport } from './routes/ex3/index'
import { Route as Ex2IndexRouteImport } from './routes/ex2/index'
import { Route as Ex1IndexRouteImport } from './routes/ex1/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Ex3IndexRoute = Ex3IndexRouteImport.update({
  id: '/ex3/',
  path: '/ex3/',
  getParentRoute: () => rootRouteImport,
} as any)
const Ex2IndexRoute = Ex2IndexRouteImport.update({
  id: '/ex2/',
  path: '/ex2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Ex1IndexRoute = Ex1IndexRouteImport.update({
  id: '/ex1/',
  path: '/ex1/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ex1': typeof Ex1IndexRoute
  '/ex2': typeof Ex2IndexRoute
  '/ex3': typeof Ex3IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ex1': typeof Ex1IndexRoute
  '/ex2': typeof Ex2IndexRoute
  '/ex3': typeof Ex3IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ex1/': typeof Ex1IndexRoute
  '/ex2/': typeof Ex2IndexRoute
  '/ex3/': typeof Ex3IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ex1' | '/ex2' | '/ex3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ex1' | '/ex2' | '/ex3'
  id: '__root__' | '/' | '/ex1/' | '/ex2/' | '/ex3/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Ex1IndexRoute: typeof Ex1IndexRoute
  Ex2IndexRoute: typeof Ex2IndexRoute
  Ex3IndexRoute: typeof Ex3IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ex3/': {
      id: '/ex3/'
      path: '/ex3'
      fullPath: '/ex3'
      preLoaderRoute: typeof Ex3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ex2/': {
      id: '/ex2/'
      path: '/ex2'
      fullPath: '/ex2'
      preLoaderRoute: typeof Ex2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ex1/': {
      id: '/ex1/'
      path: '/ex1'
      fullPath: '/ex1'
      preLoaderRoute: typeof Ex1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Ex1IndexRoute: Ex1IndexRoute,
  Ex2IndexRoute: Ex2IndexRoute,
  Ex3IndexRoute: Ex3IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
